# Generated by Django 4.0.4 on 2022-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_ht', models.FloatField()),
                ('vat', models.FloatField()),
                ('ordered_inventory', models.IntegerField(default=0)),
                ('max_inventory', models.IntegerField()),
            ],
        ),
    ]
